sudo: required
services:
  - docker

before_install:
  - docker build -t raytabuan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raytabuan/docker-react npm run test 

language: generic
